server {
    listen 80;
    server_name *.edge.local;

    location = /health {
        default_type text/plain;
        return 200 "ok\n";
    }

    location ~ ^/edge-proxy/([^/]+)(/?.*)$ {
        # $1 是域名 (ni3.edge.local)
        # $2 是剩余路径 (例如 / 或 /index.html)
        
        proxy_pass http://frps:7080$2$is_args$args;
        proxy_http_version 1.1;
        proxy_set_header Host $1;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frps:7080;
        proxy_http_version 1.1;
        proxy_set_header Host $host; # 必须透传域名，frps 靠这个识别是哪个 Edge Node
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
