upstream odoo {
    server web:8069; # 对应 web (crose_web) 容器的 8069，compose 中服务名为 web
}

upstream odoochat {
    server web:8072; # 对应 web (crose_web) 容器的 8072 (Longpolling/Websocket)
}

server {
    listen 18069;
    server_name localhost;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    # 1. 拦截并分流 WebSocket 请求到 8072
    location /websocket {
        proxy_pass http://odoochat;
        proxy_http_version 1.1; # WebSocket 升级必须使用 HTTP/1.1，否则握手失败
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. 拦截并分流常规 HTTP 请求到 8069
    location / {
        proxy_pass http://odoo;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }

    gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
    gzip on;
}
