services:
  frpc:
    image: {{URL}}:{{Nexus Mapped Port}}/repository/crose/frpc-{{OS Distribution}}:v1.0  # 官方镜像
    container_name: frpc
    restart: always
    volumes:
      # 挂载整个配置文件夹，方便 frpc 写入 dynamic_proxies.json
      - ./config/frpc:/etc/frp
      # 如果需要同步系统时间（防止认证失效）
      - /etc/localtime:/etc/localtime:ro
    # 容器启动命令，指向挂载后的配置文件路径
    command: ["-c", "/etc/frp/frpc.toml"]
    # 如果 frp 需要映射大量随机端口，建议使用 host 模式提升网络效率
    # 如果只需固定几个端口，可改用 ports 映射
    network_mode: host

  gmqtt:
    image: {{URL}}:{{Nexus Mapped Port}}/repository/crose/gmqtt-{{OS Distribution}}:v1.0
    working_dir: /gmqtt_data
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    volumes:
      - ./config/gmqtt:/etc/gmqtt
      - crose_gmqtt:/gmqtt_data
    command: ["gmqttd", "start", "-c", "/etc/gmqtt/gmqttd.yml"]
    networks:
      - crose-net

  node-red:
    image: {{URL}}:{{Nexus Mapped Port}}/repository/crose/node-red-dev:5.0.0-beta.1
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./config/node-red/settings.js:/data/settings.js
      - crose_nodered:/data
    environment:
      - npm_config_registry=http://{{URL}}:{{Nexus Mapped Port}}/repository/nrnpm/
    networks:
      - crose-net

  redis:
    image: {{URL}}:{{Nexus Mapped Port}}/repository/crose/redis:7-alpine
    container_name: crose_gateway_redis
    restart: always
    command:
      - sh
      - -c
      - test -f /data/users.acl || touch /data/users.acl; exec redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - crose_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crose-net

volumes:
  crose_gmqtt:
  crose_nodered:
  crose_redis:

networks:
  crose-net:
    name: crose-net