FROM node:22 AS web-builder

ARG NPM_REGISTRY=https://registry.npmmirror.com

COPY web/ /web/
WORKDIR /web
RUN npm config set registry ${NPM_REGISTRY}
RUN npm install
WORKDIR /web/frps
RUN npm run build

FROM golang:1.25 AS building

WORKDIR /building

ARG GOPROXY=https://goproxy.cn,direct
ARG GOSUMDB=sum.golang.org

ENV GO111MODULE=on
ENV GOPROXY=${GOPROXY}
ENV GOSUMDB=${GOSUMDB}

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY --from=web-builder /web/frps/dist /building/web/frps/dist

RUN env CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -tags frps -o bin/frps ./cmd/frps

FROM alpine:3.23

RUN apk add --no-cache tzdata

COPY --from=building /building/bin/frps /usr/bin/frps

ENTRYPOINT ["/usr/bin/frps"]
