services:
  frps:
    image: frp/frps:local
    container_name: crose_frps
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-for-frps
    restart: unless-stopped
    command: ["-c", "/etc/frp/frps.toml"]
    ports:
      - "17000:7000"
      - "17000:7000/udp"
      - "17500:7500"
    volumes:
      - "./conf/frps.toml:/etc/frp/frps.toml:ro"
